// <auto-generated />
namespace SmartTraining.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class course_Optional_columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(course_Optional_columns));
        
        string IMigrationMetadata.Id
        {
            get { return "201809202209235_course_Optional_columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
