// <auto-generated />
namespace SmartTraining.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class course_Remove_Instructor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(course_Remove_Instructor));
        
        string IMigrationMetadata.Id
        {
            get { return "201809202225042_course_Remove_Instructor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
